const express = require('express');
const authControllers = require('../controllers/adminauth');
const router = express.Router();
const dotenv = require('dotenv');
const mysql = require('mysql');
const app = express();
const cookieParser = require("cookie-parser");
const session = require('express-session');
var jsforce = require('jsforce');
app.set('view engine', 'ejs');
app.set('view engine', 'hbs');
router.post('/register', authControllers.register);
router.post('/login', authControllers.login);
router.post('/addproducts', authControllers.addproducts);
router.post('/editproducts', authControllers.editproducts);
router.post('/dashboard', authControllers.dashboard);
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
module.exports = router;