const express = require('express');
const authController = require('../controllers/auth');
const router = express.Router();
const dotenv = require('dotenv');
const mysql = require('mysql');
const app = express();
const cookieParser = require("cookie-parser");
const session = require('express-session');
var jsforce = require('jsforce');
app.set('view engine', 'ejs');
app.set('view engine', 'hbs');
router.post('/register', authController.register);
router.post('/login', authController.login);
router.post('/home', authController.view);
router.post('/addcart', authController.addtocart);
router.post('/removecart', authController.removetocart);
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
module.exports = router;